### ISSUE TITLE
License

### ISSUE THREAD

**Issue by emerson-h** [rossanez/KGen#2]
Hi @rossanez I came across this repo while doing some research for a hack-a-thon in the EU, and there is no license specified.

Here's a guide from GitHub on adding an open source license using their templates:

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by qibin-integral** [comment]
@rossanez it's default to not open-source if there isn't a license. Would you please add a license to your repo?

**Comment by rossanez** [comment]
Added CC-BY-4.0, the same applied to the main paper.
Included in 54332c7a856e86ae1272a2292e5d7b7b81aca4f6
